baseurl = "https://www.esnog.net/gore33" # Hostname (and path) to the root.
title = "ESNOG/GORE Reunion 33" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "es" # The site’s language code used to generate RSS.
defaultcontentlanguage = "es" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "" # Author's name.
    info = "Reunion no. 33 del Grupo de Operadores de Red Español (ESNOG)" # Author's job title or info.
    description = "GORE 33 website" # Site description.
    keywords = "esnog,gore33,internet" # Site keywords.
    #avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
    avatarurl = "img/esnog33-framed.png"

    footercontent = "Accede a mas detalles del evento en las entradas del menu superior" # Add footer content
    #fixedbarContent = "Accede a mas detalles del evento en las entradas del menu superior" # Add fixedbar content
    #fixedbarContentAfter = "Gracias por tu interes. Compartelo si te gusta →" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "img/esnog-30-altxcf.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/esnog1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/company/esnog/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "Telegram"
    weight = 4
    url = "https://t.me/esnog_es"
# Menu links
[[menu.main]]
    name = "Registro"
    weight = 1
    url = "registro"
[[menu.main]]
    name = "Agenda"
    weight = 2
    url  = "agenda"
[[menu.main]]
    name = "Acerca de ESNOG"
    weight = 3
    url = "about"
[[menu.main]]
    name = "Patrocinio"
    weight = 4
    url = "patrocinio"
